### ISSUE TITLE
Can I use this, when we need to call await for job which is in same file

### ISSUE THREAD

**Issue by Ganesh-Ponipireddy** [Codex-/await-local-workflow-run#94]
Can I use this, when we need to call await for job which is in same file?

Jobs:
` use_api:
    runs-on: ubuntu-latest
    steps:
        run: |
          sleep 20`

next step is your await method

**Comment by Codex-** [comment]
If this is between multiple jobs you can use `needs` syntax typically:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
